### ISSUE TITLE
reading preprocessed data

### ISSUE THREAD

**Issue by Jardic** [drivenbyentropy/aptasuite#100]
Is it somehow possible to use preprocessed sequences (variable regions only) in whatever format instead of the raw fastq files for aptaClust? I'd find this very useful.

kind Regards
Jarda

**Comment by drivenbyentropy** [comment]
Not quite but this could be be accomplished using the ```RawReader``` file format option when parsing the sequence files (one file per selection cycle). This file format simply contains one sequence per line without any additional information. You might however have to add artificial flanking primers to the sequences and specify these in your configuration file (or the import wizard) as I have yet to implement parsing without primers. 

Hope this helps!

**Comment by Jardic** [comment]
Sure, this helps, thank you for the tip!
