### ISSUE TITLE
Running Aptatrace ignoring primer regions

### ISSUE THREAD

**Issue by shumpeim** [drivenbyentropy/aptasuite#102]
Hello!

I have very little coding experience, and I was wondering if it was possible to run AptaTrace without the primer regions being involved in structure prediction. My SELEX experiment removed the primer regions in secondary structure formation by incubation with primer-binding oligos. So in motif analysis I'd like that not to be included as well. 

Is it possible?

Thanks for any help!

**Comment by drivenbyentropy** [comment]
Hi @shumpeim,

Thank you for reporting this. As of the latest version of AptaSuite (v0.9.7b), this is now possible by using the new Batch Mode feature. I have updated the [wiki](https://github.com/drivenbyentropy/aptasuite/wiki/Importing-HTS-data) accordingly. 

While you cannot directly instruct AptaSuite to ignore primers during the secondary structure prediction phase, this can now be accomplished in the following way:

* Download the newest version of AptaSuite 
* Use AptaSuite’s export function (under Experiment->Export Data) and export all the selection cycles. Make sure that you do not have the ‘primer export’ option checked under Additional Options. Alternatively, you could use any other third party program to demultiplex your data and save the sequences without primers in fastq files (one per selection cycle).
* Create a new Experiment in AptaSuite and choose `IS Demultiplexed` and `Single End` under the Sequencing Information section.
* In the next window, check the `Batch Mode` option and follow the reminder of the instructions on screen.

Please do let me know if this solves your issue.
