### ISSUE TITLE
Aptasuite on macOS Monterey

### ISSUE THREAD

**Issue by k-fhung** [drivenbyentropy/aptasuite#106]
Can someone provide an instruction for installing Aptasuite on macOS Monterey?
Very much appreciated.

**Comment by so-susan** [comment]
Installing aptasuite is extremely easy and straightforward once you have the right version of java (with fx). The easiest way to get the right java that I have found is by using sdkman https://sdkman.io/install - after installing sdkman, I used it to install liberica with fx. i.e., in unix terminal, type: ``sdk install java 17.0.2.fx-librca``  and let it become default unless you want to be more custom with your java dependencies (which sdkman will help you do). 

I struggled a lot with getting java to work and beofre the only solution i found was to get maven working and then compile aptasuite locally; using a jdk with fx included enabled me to use the precompiled version as explained in the wiki.
