### ISSUE TITLE
GUI - works only once

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#12]
Hi,
So I've tried to use the GUI to analyze real-data derived sequences from one of the rounds from my selection. The file is quality-checked fastq after paired-reads joining done elsewhere.
I setup the experiment and run the parsing, and it worked nicely. However, after setting up another experiment (even a similar one with slighly different parameters/different folder) I get an error - the parsing is completed within a split second, nothing is displayed at Experiment Overview (blank background), and when I switch to other tabs they're loading infinitely. I can however open the first experiment which worked, and it's fine.

Please find the configuration file and the log attached.
[configuration.aptasuite_.txt](https://github.com/drivenbyentropy/aptasuite/files/1731519/configuration.aptasuite_.txt)
[log_2018-02-16_14-39-25.txt](https://github.com/drivenbyentropy/aptasuite/files/1731521/log_2018-02-16_14-39-25.txt)

I'm using aptasuite-0.5.3 on Windows 10.

edit:
I've tried it on another computer with a fresh download and freshly installed JAVA. No luck, doesn't even analyze the data once. Parsing takes a split second and no results are produced.

**Comment by drivenbyentropy** [comment]
Please check if version [v0.5.4](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.5.4) fixes this issue. I believe this was due to the configuration not being cleared correctly creating a mix between the old and the new experiment.

**Comment by PJpb** [comment]
Dear drivenbyentropy,
The new version v0.5.4 is not working when used from command line.
Please check the files attached. 
[log_2018-02-16_21-08-59.txt](https://github.com/drivenbyentropy/aptasuite/files/1732668/log_2018-02-16_21-08-59.txt)
[powershell_log.txt](https://github.com/drivenbyentropy/aptasuite/files/1732669/powershell_log.txt)
[cfg.txt](https://github.com/drivenbyentropy/aptasuite/files/1732670/cfg.txt)
(I had to change the file to .txt for the github to support the upload; it was .fastq)
[1302_merged_1000seq_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1732672/1302_merged_1000seq_txt.txt)

**Comment by PJpb** [comment]
Dear drivenbuentropy,
Unfortunetely neither the GUI nor command line v0.5.4 is working at all now.

For the GUI: when I pressed "Import Data" for the first time I instantly got "Parsing completed". Here are the files:
[log_2018-02-16_21-14-54.txt](https://github.com/drivenbyentropy/aptasuite/files/1732693/log_2018-02-16_21-14-54.txt)
[configuration.aptasuite.txt](https://github.com/drivenbyentropy/aptasuite/files/1732694/configuration.aptasuite.txt)
(Configuration changed to .txt due to github requirements)

When I tried it for the second time (with different folder paths for output data), aptasuite shut down after pressing "Import data".
[log_2018-02-16_21-17-26.txt](https://github.com/drivenbyentropy/aptasuite/files/1732700/log_2018-02-16_21-17-26.txt)
[configuration.aptasuite.txt](https://github.com/drivenbyentropy/aptasuite/files/1732701/configuration.aptasuite.txt)
(Same source data file)


Also the command line version is not working. Please find the files attached.
[powershell_log.txt](https://github.com/drivenbyentropy/aptasuite/files/1732703/powershell_log.txt)
[log_2018-02-16_21-08-59.txt](https://github.com/drivenbyentropy/aptasuite/files/1732704/log_2018-02-16_21-08-59.txt)
[cfg.txt](https://github.com/drivenbyentropy/aptasuite/files/1732705/cfg.txt)
(Same source data file)

**Comment by drivenbyentropy** [comment]
Yep, I think there was another bug which caused this behavior. Could you please try with version [v0.5.5](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.5.5)? This should now correctly open and close experiments.

Thanks

**Comment by drivenbyentropy** [comment]
Hmmm, this should however not affect the CLI version.

**Comment by PJpb** [comment]
Sorry, I was pretty sure that I've uploaded the source file as well!
Here it is:
[1302_merged_1000seq_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1732783/1302_merged_1000seq_txt.txt)
(converted from fastq to txt for github compatibility)

**Comment by PJpb** [comment]
No luck with CLI:
[cfg3.txt](https://github.com/drivenbyentropy/aptasuite/files/1732809/cfg3.txt)
[1302_merged_1000seq_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1732810/1302_merged_1000seq_txt.txt)
[log_2018-02-16_21-55-43.txt](https://github.com/drivenbyentropy/aptasuite/files/1732811/log_2018-02-16_21-55-43.txt)
[powershell_log.txt](https://github.com/drivenbyentropy/aptasuite/files/1732819/powershell_log.txt)

**Comment by PJpb** [comment]
No luck with GUI either (v0.5.5), "Parsing completed" within a split second, no data output. As if it didn't see any sequences in the file?
Source file: [1302_merged_1000seq_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1732849/1302_merged_1000seq_txt.txt)
Configuration created by aptasuite: 
[configuration.aptasuite_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1732850/configuration.aptasuite_txt.txt)
Log: 
[log_2018-02-16_22-04-26.txt](https://github.com/drivenbyentropy/aptasuite/files/1732851/log_2018-02-16_22-04-26.txt)

**Comment by drivenbyentropy** [comment]
Thanks for the sequence file. I can now reproduce the error and looking into the cause. I suspect this might have something to do with the pre-processing done to the file as this is really the only difference between my tests and yours. Let me see what I can find.

Thanks for all your help!

**Comment by drivenbyentropy** [comment]
I figured it out.  Its the encoding of the sequence file... The file is encoded in `UCS-2 LE BOM` however AptaPlex expects `UTF-8`. Did you progress the file on Windows?

**Comment by PJpb** [comment]
Yes, I did - I cut out first 4k lines of the original sequencing file (after QC and all done via Galaxy server). But I'm using a soft that allows to change the coding. I'll give it a try in a sec.

**Comment by PJpb** [comment]
Ok, so for CLI v0.5.6:
1. exactely as you've said, changing to UTF-8 works fine! Thank you for pointing this out, and sorry for bothering you with such nonsense. It works for a file with merged QCed reads [1302_merged_utf8_1000seq_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1732977/1302_merged_utf8_1000seq_txt.txt)
[cfg4.txt](https://github.com/drivenbyentropy/aptasuite/files/1732991/cfg4.txt)


2. However it still crashes for two pre-merged paired-end files (not groomed, raw data I've got from NGS supplier).
[1302_raw_fwd_utf8_1000seq_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1732978/1302_raw_fwd_utf8_1000seq_txt.txt)
[1302_raw_rev_utf8_1000seq_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1732979/1302_raw_rev_utf8_1000seq_txt.txt)
[cfg7.txt](https://github.com/drivenbyentropy/aptasuite/files/1732995/cfg7.txt)
[log_2018-02-16_23-14-51.txt](https://github.com/drivenbyentropy/aptasuite/files/1732999/log_2018-02-16_23-14-51.txt)
[powershell_log.txt](https://github.com/drivenbyentropy/aptasuite/files/1733007/powershell_log.txt)

I'll test the GUI now.

**Comment by drivenbyentropy** [comment]
Thanks for the update. The GUI should give the same results as both CLI and GUI call the same parsing library.

**Comment by PJpb** [comment]
Should ;)
GUI still does not parse anything, i.e. the parsing completes momentarily.
![image](https://user-images.githubusercontent.com/32843053/36332041-c6054266-1370-11e8-9cf0-fbab72959ff9.png)
And there's no output whatsoever.
Source file: [1302_merged_utf8_1000seq_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1733018/1302_merged_utf8_1000seq_txt.txt)
Aptasuite configuration: 
[configuration_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1733020/configuration_txt.txt) (quite a lot of backslashes in filepaths)
Log:  [log_2018-02-16_23-25-09.txt](https://github.com/drivenbyentropy/aptasuite/files/1733023/log_2018-02-16_23-25-09.txt)

Also, when I've tried to File->Open Experiment and used the configuration file from this run, aptasuite closed down with no error message, but it did produce a log: 
[log_2018-02-16_23-26-52.txt](https://github.com/drivenbyentropy/aptasuite/files/1733024/log_2018-02-16_23-26-52.txt)

**Comment by drivenbyentropy** [comment]
That is so strange, I cannot reproduce the GUI issue here, with the same files... Is your drive `E:` a network drive by any chance? If so, could you try running this with all data and experiment folder on a local drive?

**Comment by PJpb** [comment]
It's a local drive.
Are you trying to reproduce it using Windows?

I'll try to run it using a virtual machine with a UNIX system.

**Comment by drivenbyentropy** [comment]
I'm running it on a Windows machine, yes.

**Comment by drivenbyentropy** [comment]
No issues running on my Linux setup either. GUI and CLI are working with the merged file. I am running out of ideas as to what might be the cause here.

**Comment by PJpb** [comment]
Sorry, didn't see your comment edit.
`Can you start the GUI via Powershell on Windows (just run aptasuite without any parameters) and do the import again. Then paste the output of the console? It should at least indicate where it gets stuck.`
[console_output.txt](https://github.com/drivenbyentropy/aptasuite/files/1733138/console_output.txt)

`WARNING: Loading FXML document with JavaFX API of version 9 by JavaFX runtime of version 8.0.161` Am I wasting your time again?...

**Comment by drivenbyentropy** [comment]
You are not wasting my time, on the contrary :).

The warning however has nothing to do with the bug. The console log on the other side has some juicy stuff in it ;-). 

Btw. the paired end case should be fixed now as well --> [v0.5.7](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.5.7)

Thanks!

**Comment by PJpb** [comment]
My last try today, it's 1 AM ;) Will update this comment when I run it.

**Comment by drivenbyentropy** [comment]
Thank you again for all your help and dedication, I really appreciate it :+1: 

I will try to solve the remaining issues asap.

**Comment by PJpb** [comment]
I'm glad that you're not discouraged by me spamming you with the issues. You're really doing a great job!

I've just run the v0.5.7 GUI to import data, the situation is a bit different: after hitting the button, some information does show up in gray (instead of "Parsing completed"), but then the whole application closes down before I even read it. But I've managed to make a print screen.
![image](https://user-images.githubusercontent.com/32843053/36335206-6ea64c64-137e-11e8-94ed-e4e8592667c4.png)

Here are the files:
[configuration_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1733193/configuration_txt.txt)
[log_2018-02-17_01-03-16.txt](https://github.com/drivenbyentropy/aptasuite/files/1733194/log_2018-02-17_01-03-16.txt)
[console_log.txt](https://github.com/drivenbyentropy/aptasuite/files/1733195/console_log.txt)
Hope that helps.
Keep up the good job!

**Comment by drivenbyentropy** [comment]
"Awesome" ;-) 

This helps a lot, thank you. It seems that the only difference between mine and your setup is that you are running Windows 10 and I am running Windows 7. If you get the chance next week, could you report the outcome when running this in a VM using Linux? I on the other hand will try to get my hands on a Windows 10 machine. 

Again, thank you so much for your help and please do not hesitate to report any additional issues you may encounter.

Cheers!

**Comment by PJpb** [comment]
It looks like I owe you an apology for having wasted your time. It seems that E:\OneDrive\ is treated as a network drive. When I moved all the files to a folder on E:\ it seems to work.
I will give it a couple of more tries over the weekend anyway.

**Comment by drivenbyentropy** [comment]
No worries, I am glad we are getting to the bottom of it :)

Edit2 is interesting. How was the first experiment created? Using the powershell as SU or by double-clicking? If possible could you test the following scenarios?

* Double Click -> Create two experiments, and open previous one 
* PowerShell -> Create two experiments and open previous one
* Create one with Double Click and one with Powershell and open in either combination.

I am testing the development branch almost exclusively using Powershell when on Windows but I believe it is not running as superuser.

Thanks!

**Comment by drivenbyentropy** [comment]
Can this ticket be considered fixes as well now that #14 is closed?

**Comment by PJpb** [comment]
Seems to work as well.
