### ISSUE TITLE
Aptasuite

### ISSUE THREAD

**Issue by chay337681** [drivenbyentropy/aptasuite#122]
Hello when downloaded the new aptasuite latest version, there's no exe. files to install. Please advise. 
https://github.com/drivenbyentropy/aptasuite/releases

**Comment by drivenbyentropy** [comment]
Hi,

Provided you have Java installed correctly, you should be able to start AptaSuite by double clicking on the ```aptasuite-0.9.8.jar``` file. Please also refer the the [Wiki](https://github.com/drivenbyentropy/aptasuite/wiki/Basic-Usage) for more information on how to run this software. 

Thanks!
