### ISSUE TITLE
Import Data for AptaPLEX is too long

### ISSUE THREAD

**Issue by CTPAHHIK38RUS** [drivenbyentropy/aptasuite#124]
Hello, I have successfully installed AptaSuite, but I have a problem again. I have a set of HTSeq data from different selection rounds. When I use them to generate a configuration file, the window does not hang, but there are no changes either. As I understood from the number of rejected sequences with the wrong alphabet, I need to delete the metadata after the > sign, and leave only the sequence itself? I also attach a data set and logs.
My procedure:
1. New Experiment
2. Write name and description analysis, project path.
3. Sequencing information - IS DEMULTIPLEXED (File per round)
4. Single end
5. File format - FASTQ
6. Batch mode (without primers)
7. Region size - exact length 40
8. Add selection cycles
9. Then import data
And there what i have (screenshot)
![image](https://github.com/drivenbyentropy/aptasuite/assets/119832863/4eaba4ce-7f97-489b-b546-ee876beaf034)

There is my log file and data set. 
[log_2023-06-10_17-55-59.txt](https://github.com/drivenbyentropy/aptasuite/files/11730986/log_2023-06-10_17-55-59.txt)
[Library.zip](https://github.com/drivenbyentropy/aptasuite/files/11731015/Library.zip)

What am I doing wrong?

**Comment by CTPAHHIK38RUS** [comment]
Okay, I found what the problem was. I removed the > and metadata, leaving only the sequences. Aptosuite successfully loads them one by one and outputs statistics. But when loading all the loops, it still gets stuck on running AptaPLEX.
I also attach a data set
![image](https://github.com/drivenbyentropy/aptasuite/assets/119832863/ce37e76b-cd28-48a7-ab84-47a87b0fb144)
[seq.zip](https://github.com/drivenbyentropy/aptasuite/files/11741693/seq.zip)

**Comment by drivenbyentropy** [comment]
Hi. 

Did AptaSuite create a log file for the latter case? If so, could you please attach it? 

Thanks!

**Comment by CTPAHHIK38RUS** [comment]
Hi, now all functional working. Unfortunately, I have already deleted the log file of that case.

**Comment by CTPAHHIK38RUS** [comment]
I think the problem can be considered solved
