### ISSUE TITLE
GUI - Aptamer Family Analysis - table sorting bug

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#13]
Hi,
Sorting of the table on the left panel of Aptamer Family Analysis works as long as I don't click any of the clusters. When I click any cluster, change the sorting type and press GO, the table disappears.
[log_2018-02-16_16-22-08.txt](https://github.com/drivenbyentropy/aptasuite/files/1731811/log_2018-02-16_16-22-08.txt)
[log_2018-02-16_16-22-48.txt](https://github.com/drivenbyentropy/aptasuite/files/1731812/log_2018-02-16_16-22-48.txt)

**Comment by drivenbyentropy** [comment]
Fixed with 0815e4320991d6c1c3917ddc0096e370856b78aa and version [v0.5.8](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.5.8)

**Comment by PJpb** [comment]
I checked for a small subset of data (a few clusters) - seem to work when I fiddle with it back and forth.
