### ISSUE TITLE
Cannot export data from GUI

### ISSUE THREAD

**Issue by molecularengineering** [drivenbyentropy/aptasuite#130]
I'm running Aptasuite (latest version) in Windows with a GUI. When I click "experiment" and "export data", it leads me to the export window, but there is no "export" icon to click for exporting. Any suggestions/insight would be greatly appreciated.

**Comment by drivenbyentropy** [comment]
Hi, 

Could this be an issue of screen resolution? If possible, could you please provide a screenshot of the issue?

Thanks!

**Comment by molecularengineering** [comment]
Thank you so much for such a quick reply!!! Here is a screenshot.
<img width="960" alt="image" src="https://github.com/drivenbyentropy/aptasuite/assets/164352238/e833728e-c73d-4c83-a96b-9eebebf28044">

**Comment by molecularengineering** [comment]
I should add that once I open this window, there doesn't seem to be any way to close it. There is no "x" at the top right of the window. Also, the pop-up icon that appears when I hover over the aptasuite icon on the toolbar does have an "x" but clicking on it does nothing.
<img width="960" alt="image" src="https://github.com/drivenbyentropy/aptasuite/assets/164352238/a5152338-2d21-421f-9970-3f5b1074f2c5">

**Comment by molecularengineering** [comment]
I should add that clicking on the "X" at the top right does not close the window. There doesn't seem to be any way to close the "export" window once it is open.

**Comment by molecularengineering** [comment]
I changed the scale of my screen to 125% from 150% and the "export" icon appeared. Thanks for the advice!!!! I will post again if I run into any other problems.

**Comment by drivenbyentropy** [comment]
Happy to hear the issue is resolved.
