### ISSUE TITLE
GUI - Aptamer Family Analysis - re-clustering doesn't work

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#15]
When the clusters are already computed and I press the "Run AptaCluster" button, I get prompted for confirmation (yes), then the "loading" icon is displayed in the top-left corner of the app (and it moves around off the edge of the window so it disappears repeatedly):
![image](https://user-images.githubusercontent.com/32843053/36314442-2d3a1d80-1335-11e8-955b-dc87e741efce.png)
And nothing else happens. No clusters are generated.

**Comment by drivenbyentropy** [comment]
I believe this was an artifact of previous bugs and should be fixed with (v0.5.8)[https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.5.8]. Please re-open if the bug persists.
