### ISSUE TITLE
GUI - Aptamer Pool Table does not finish loading under certain circumstances

### ISSUE THREAD

**Issue by drivenbyentropy** [drivenbyentropy/aptasuite#18]
Due to a bug in sorting the aptamers, sometimes the screen loads indefinitely. See (comment)[https://github.com/drivenbyentropy/aptasuite/issues/12#issuecomment-366445887] in #12.

**Comment by drivenbyentropy** [comment]
Fixed with abb0987bec8f23f937d43eaab6d5a111a7c53a8b and [v0.5.9](https://github.com/drivenbyentropy/aptasuite/releases/edit/v0.5.9)

**Comment by PJpb** [comment]
It did load. However, that was it. No aptamers could be displayed after clicking "go".
Please find the logs below.
[configuration_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1736940/configuration_txt.txt)
[console_log_AptamerPoolErr.txt](https://github.com/drivenbyentropy/aptasuite/files/1736935/console_log_AptamerPoolErr.txt)
[log_2018-02-19_14-56-42.txt](https://github.com/drivenbyentropy/aptasuite/files/1736942/log_2018-02-19_14-56-42.txt)

PS:
Preparing to sort data
Retrieving data for selection cycle r1302
Prioritizing data
HEREeee
HERE
Sorting data
Creating Table and Pagination

😃
