### ISSUE TITLE
GUI v0.5.9 - LSH dimensions drop-down menu

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#19]
The LSH dimensions drop-down menu shows only a few numbers to choose from. Is that correct?
![image](https://user-images.githubusercontent.com/32843053/36351655-8871708a-14ad-11e8-8129-b77aba1c3093.png)
If I choose smth else than 33 (default), then I cannot even go back to 33. 
![image](https://user-images.githubusercontent.com/32843053/36351659-98919594-14ad-11e8-957e-90c91d82a6a8.png)

**Comment by drivenbyentropy** [comment]
in [v0.6.3](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.6.3).
