### ISSUE TITLE
AptaSuite on Win10

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#2]
Hi there,
First of all - great work! I hope I will be using it soon!
I've got a problem though, which surely is caused by my lack of computer/bioIT skills (and these are indeed pretty low, so please forgive me if the question is lame)
I tried to run the aptasuite on a fresh install of Windows 10, but it crashes when trying to create the database (for I've not set up any of course). Log says (Windows powershell):
> Creating Database
> Error invoking construtor of AptamerPool backend
> java.lang.reflect.InvocationTargetException
>        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
>        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
>        at java.lang.reflect.Constructor.newInstance(Unknown Source)
>        at lib.aptamer.datastructures.Experiment.<init>(Experiment.java:132)
>        at aptasuite.CLI.createDatabase(CLI.java:234)
>        at aptasuite.CLI.<init>(CLI.java:115)
>        at aptasuite.Aptasuite.main(Aptasuite.java:40)
> Caused by: java.lang.OutOfMemoryError: Java heap space
>        at java.util.BitSet.initWords(Unknown Source)
>        at java.util.BitSet.<init>(Unknown Source)
>        at orestes.bloomfilter.memory.BloomFilterMemory.<init>(BloomFilterMemory.java:15)
>        at orestes.bloomfilter.FilterBuilder.buildBloomFilter(FilterBuilder.java:251)
>        at lib.aptamer.datastructures.MapDBAptamerPool.<init>(MapDBAptamerPool.java:82)
>        ... 8 more
> Error invoking AptamerPool backend

So my question is - what other software/libraries do I need for the suite to be able to set up a database? Or should I set it up myself beforehand, and if so - how do I do that? Or is the issue due to something else entirely?

I would much appreciate your help, as AptaSuite seems to be the only free tool with such capabilities. Also, maybe this issue will help you to improve the guide so the suite is even more accessible!

Best regards,
PJ

**Comment by PJpb** [comment]
Hi there,
Indeed it worked, thank you for your quick answer! It was a memory issue, as I was running a 32bit Java, which has a 2Gb limit for heap space. I changed to 64bit and I could set the limit high enough for the suite to run properly.

I've got another issue though - AptaCLUSTER is not exporting any reports. While AptaPLEX works fine and I do obtain a pool.fastq file with frequencies, after running *-cluster* option and *-export pool,cycles,clusters", no additional file is being created.
If that issue is not to be fixed easily, is there a way to view the entire database .mapdb somehow?

**Comment by PJpb** [comment]
Hi there,
Thank you for your quick response and help - it worked. It was indeed a memory issue, as I was running a 32bit Java, which has a 2Gb limit for heap space. I changed to 64bit and I could set the limit high enough for the suite to run properly.
Great job and thank you once again!

**Comment by PJpb** [comment]
Hi,
Back again. So the AptaSuite works great, and it's really quick! (even though it doesn't use much of my computer resources)
My question however is: how do I make AptaGUI to use the database created by AptaSuite? Do I have to setup a MYSQL local server?

Also, when starting AptaGUI from Windows Powershell, I see a list of errors (log in the attached file), but the GUI starts fine nonetheless.

Best,
PJ
[aptaGUI_error_log.txt](https://github.com/drivenbyentropy/aptasuite/files/1398259/aptaGUI_error_log.txt)

**Comment by drivenbyentropy** [comment]
Hi,

AptaGUI and any previous implementations of AptaTrace, AptaCluster, etc are not compatible with AptaSUITE. At the moment, AptaSUITE is a command line application only. I am currently working on the graphical user interface although it might take a while to complete as I am rewriting it from scratch. 

I will add a clarification of the current state of this software to the Wiki.
