### ISSUE TITLE
GUI v0.5.9 - AptaPLEX Advanced Options bug

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#20]
Changing any setting in the Advanced Options in the experiment wizard produces a bug that prevents the parsing later.
[log_2018-02-18_13-26-00.txt](https://github.com/drivenbyentropy/aptasuite/files/1734698/log_2018-02-18_13-26-00.txt)
[configuration_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1734699/configuration_txt.txt)
[console_log.txt](https://github.com/drivenbyentropy/aptasuite/files/1734700/console_log.txt)

**Comment by drivenbyentropy** [comment]
Should be fixed in [v0.6.2](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.6.2). Please test and close if it works. Thanks!

**Comment by PJpb** [comment]
Works fine!
