### ISSUE TITLE
GUI v0.6.3 - Experiment Overwiew issues

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#22]
I'm back ;)
![image](https://user-images.githubusercontent.com/32843053/36416342-163d8512-1629-11e8-905e-5d31f5840d3f.png)
Minor issues - please take a look at "Selection cycle percentage" - what does it exactely represent? The input was two files from paired-end reads, i.e. 10k forward and 10k reverse reads. Why is it 10.57%?

Also, the numbers on the Randomized Region Size are unordered.

edit: Selection cycle percentage might be connected to #23.

**Comment by drivenbyentropy** [comment]
Thanks for the report :) 
Please let me know if commit f7c2a7194b636443df69299f8b9efe69bdc04c72 fixes this. Is should also fix #23 and is implemented in version [v.0.6.5](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.6.5)

**Comment by PJpb** [comment]
Fixed indeed.

**Comment by PJpb** [comment]
The numbers on the Randomized Region Size chart are still not always ordered.
![image](https://user-images.githubusercontent.com/32843053/36736172-38434ca0-1bd8-11e8-98e3-865e969e734e.png)

**Comment by drivenbyentropy** [comment]
Ups, forgot about that part of the ticket. It should now be fixed in [v0.6.6](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.6.6)
