### ISSUE TITLE
Large dataset error

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#25]
Ready for another round?:)

I started to analyze my real data. I first attempted to parse the data in 8 files (rounds 2-9), together they contain 43 M reads (FASTQ, QC-ed, reverse-complemented, trimmed to primers only, about 8GB of data).

I started the GUI v0.6.3 simply by double-clicking (no PowerShell). I created a new experiment and let the parsing run overnight. I've changed the bloom filter to 0.0001 (after a second though I realized that might have been a mistake due to my misunderstanding of this property. I'll set up another issue with questions regarding the performance parameters ;) )
[configuration_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1743267/configuration_txt.txt)

I started the parsing and I saw that there were some errors in the wizard windows popping up and disappearing, I managed to take print screens:
![image](https://user-images.githubusercontent.com/32843053/36469071-427ffe58-16e6-11e8-9c7b-b6c0f2056b35.png)
![image](https://user-images.githubusercontent.com/32843053/36469078-46becdaa-16e6-11e8-9f03-182e90c4a4c2.png)

In the morning the parsing was finished, but the Experiment Overview window was blank. The Sequence Analysis was fine - it did show the nucleotide distribution charts nicely for all rounds. Aptamer Pool did not load, and I haven't even tried the clusters.
As the loading log (the app log only, as there was no console open) is 12GB, I'm posting only the first 100k lines.
[log_2018-02-20_18-10-40_short_100k_lines.txt](https://github.com/drivenbyentropy/aptasuite/files/1743257/log_2018-02-20_18-10-40_short_100k_lines.txt)

I've closed the App and I've tried to reopen the experiment, starting the app via PowerShell. The App started to load the data but crashed and closed down. Here are the logs.
[log_2018-02-21_08-48-59.txt](https://github.com/drivenbyentropy/aptasuite/files/1743273/log_2018-02-21_08-48-59.txt)
[console_log_opening_an_experiment.txt](https://github.com/drivenbyentropy/aptasuite/files/1743274/console_log_opening_an_experiment.txt)

If you'd like me to perform another experiment in a chosen setup please do not hesitate, I'm fine with being a beta-tester ;)

**Comment by PJpb** [comment]
It worked when I tried for the second time, and it's working nicely now.

**Comment by drivenbyentropy** [comment]
Strange, please let me know if this is a recurring issue. Thanks!
