### ISSUE TITLE
Clusters total CPM over rounds

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#27]
I'd love a feature that is either missing, or I cannot find it/I don't know that it's there ;)

I'd like to know the frequency of the whole cluster over all rounds. E.g. when I choose a cluster to analyze, it would be great to see a chart displaying its total CPM (i.e. the size of the cluster) in subsequent rounds, to see how quickly it was enriching. Basically the feature is there but it's only shown for selected sequence in the Aptamer Pool (when I choose one sequence of the selected cluster) as the "Cardinality Chart".

**Comment by drivenbyentropy** [comment]
Good idea! 

It might take a version of two, but I will see into adding it.

Thanks!

**Comment by PJpb** [comment]
Also would be nice to be able to export only the cluster data - i.e. cluster size, diversity, total CPM in subsequent rounds, enrichment, and the seed sequence. :)

**Comment by drivenbyentropy** [comment]
You mean basically like exporting the pool data as a table but for clusters? Thats a cool idea and easily addable.
