### ISSUE TITLE
[Bug]Failure to Copile

### ISSUE THREAD

**Issue by Eggsorer** [drivenbyentropy/aptasuite#28]
I was compiling using MVN following your instruction. Bunch of errors came up:
[INFO] ------------------------------------------------------------------------
[INFO] Building AptaSUITE 0.6.3
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ aptasuite ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 30 resources
[INFO] Copying 12 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ aptasuite ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 169 source files to /home/chenli/aptasuite/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/chenli/aptasuite/src/main/java/gui/core/aptamer/family/analysis/AptamerFamilyAnalysisRootController.java:[206,27] cannot find symbol
  symbol:   class SequenceTableRowData
  location: class gui.core.aptamer.family.analysis.AptamerFamilyAnalysisRootController
[ERROR] /home/chenli/aptasuite/src/main/java/aptasuite/CLI.java:[53,19] cannot find symbol
  symbol:   class PlayGround
  location: package lib.aptanet
[ERROR] /home/chenli/aptasuite/src/main/java/gui/wizards/aptasim/AptaSimWizardController.java:[49,26] cannot find symbol
  symbol:   class AptaSimParserSoumitra
  location: package lib.parser.aptasim
[ERROR] /home/chenli/aptasuite/src/main/java/gui/core/motifs/MotifAnalysisRootController.java:[39,40] cannot find symbol
  symbol:   class SequenceTableRowData
  location: package gui.core.aptamer.family.analysis
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.834 s
[INFO] Finished at: 2018-02-23T17:56:29-08:00
[INFO] Final Memory: 47M/1282M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project aptasuite: Compilation failure: Compilation failure:
[ERROR] /home/chenli/aptasuite/src/main/java/gui/core/aptamer/family/analysis/AptamerFamilyAnalysisRootController.java:[206,27] cannot find symbol
[ERROR]   symbol:   class SequenceTableRowData
[ERROR]   location: class gui.core.aptamer.family.analysis.AptamerFamilyAnalysisRootController
[ERROR] /home/chenli/aptasuite/src/main/java/aptasuite/CLI.java:[53,19] cannot find symbol
[ERROR]   symbol:   class PlayGround
[ERROR]   location: package lib.aptanet
[ERROR] /home/chenli/aptasuite/src/main/java/gui/wizards/aptasim/AptaSimWizardController.java:[49,26] cannot find symbol
[ERROR]   symbol:   class AptaSimParserSoumitra
[ERROR]   location: package lib.parser.aptasim
[ERROR] /home/chenli/aptasuite/src/main/java/gui/core/motifs/MotifAnalysisRootController.java:[39,40] cannot find symbol
[ERROR]   symbol:   class SequenceTableRowData
[ERROR]   location: package gui.core.aptamer.family.analysis
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by drivenbyentropy** [comment]
Ups, I think I accidentally committed some files from my local development branch. I will fix this with the next commit, sorry.

Meanwhile you can use the [precompiled version](https://github.com/drivenbyentropy/aptasuite/releases/download/v0.6.3/aptasuite-0.6.3.zip)

Thanks for reporting this!

**Comment by Eggsorer** [comment]
Ran the pre-compiled files using commands as below,
java -jar aptasuite-0.6.4.jar
got the following errors,
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at aptasuite.Aptasuite.main(Aptasuite.java:82)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 13 more
--------------------------------
Looks like the pre-compile file won't run on my system?I am running on a CentOS 7.4.1708 cluster.

**Comment by drivenbyentropy** [comment]
What Java version are you running? For the GUI, you currently need Java 8.x with JavaFX support.

**Comment by Eggsorer** [comment]
(ya, sorry for the typo haha)
I'm using 1.8.0.

**Comment by drivenbyentropy** [comment]
No worries :). 

I think you are missing the `openjfx` package on your system which should provide JavaFX. Alternatively you could try to install Open JDK which also ships with JavaFX.

**Comment by Eggsorer** [comment]
OK. I'll try to install Open JDK locally. Our one and only sysadmin is on vacation. I will leave a comment here if further error should occur.

**Comment by drivenbyentropy** [comment]
Sounds good, thanks. 

Btw, if you are running AptaSuite on the cluster, you could analyze the data using the CLI feature (which does not depend on JavaFX), and then copy the experiment folder to your local machine with JavaFX support to visualize the results. 

Calling
```
java -jar aptasuite-0.6.4.jar -help
```
should should print and exit without errors. Details on how to create a configuration file can be found in the [wiki](https://github.com/drivenbyentropy/aptasuite/wiki).

Hope this helps!

**Comment by Eggsorer** [comment]
I forgot but is AptaGUI included in AptaSuite GUI too?

**Comment by drivenbyentropy** [comment]
Its not included in the traditional sense but almost all features of AptaGUI have been rewritten from scratch and integrated into AptaSuite.

**Comment by Eggsorer** [comment]
Got it. Then I do need Open JDK for visualizing Aptacluster. I can call the other functions under CLI.
Thanks for the clarification! Will keep in touch with you.
