### ISSUE TITLE
GUI v0.6.5 - Aptamer Family Analysis bug

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#30]
Hi,
I've run AptaCluster for a set of rounds (R2-R9) from GUI v0.6.5 on Windows 10. The clusters displayed are clusters from round 9 only, and it cannot be changed - the Drop Down menu on the left (Cluster sorting) doesn't seem to work properly. The screens will hopefully explain it.
![image](https://user-images.githubusercontent.com/32843053/36731278-88739efe-1bca-11e8-91ee-bb282c7176f1.png)
![image](https://user-images.githubusercontent.com/32843053/36732118-142c9f2a-1bcd-11e8-9a8c-bd565e1eea23.png)
![image](https://user-images.githubusercontent.com/32843053/36732138-260c07e4-1bcd-11e8-927e-4904e4f006ac.png)
![image](https://user-images.githubusercontent.com/32843053/36732160-37f7135e-1bcd-11e8-9f10-5a59d16f2a81.png)
After clicking "GO" the drop down menu goes back to R9.
![image](https://user-images.githubusercontent.com/32843053/36732192-4ff49954-1bcd-11e8-8aab-7d1724de82f5.png)
And I arrive at the very same clusters as before.
![image](https://user-images.githubusercontent.com/32843053/36732211-60910342-1bcd-11e8-8c68-0036f22e8924.png)

No error messages are produced in the console or in the log.

**Comment by drivenbyentropy** [comment]
Fixed in [v.0.6.8](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.6.8)
