### ISSUE TITLE
Add the ability to export cluster information analogous to how the aptamer pool is exported

### ISSUE THREAD

**Issue by drivenbyentropy** [drivenbyentropy/aptasuite#31]
See #27

**Comment by PJpb** [comment]
Hi there,
Do you plan to work on this enchancement? I'm getting back to my NGS data (awaiting new package in a few weeks), and it would make my work much much easier!

PS: A few weeks back in Oxford (UK) during Aptamers 2018 symposium, someone has mentioned your software in a speech. Can't recall who that was, but it surely was one of the more prominent aptamer science people. Congrats! ;)

**Comment by drivenbyentropy** [comment]
I have added the option to export a table containing all clusters with their id, seed sequence (and id) and frequency, diversity, and CPM for all cycles to the export wizard. This feature will be made available in AptaSuite v.0.8.5
