### ISSUE TITLE
GUI v0.6.5 - Motif analysis bug

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#32]
Hi,
The GUI produces an error when trying to display a motif analysis. I feeded it with sample data (20k sequences in two files), run the clustering and AptaMotif at alpha=2 and kmer=6. The analysis went fine (although it consumed 100% of CPU; I think that if there were more sequences to analyze the CPU would overheat over time, but it took only 3 minutes; I've got a Intel Core i7-7700HQ, so not bad for a desktop; is this normal? Can it be restricted somehow?), but when I click the analysis in the left panel nothing happens (The middle window stays blank). It seems to be caused by the float character (US "." vs European ",") again. Here are the files.
[console_log.txt](https://github.com/drivenbyentropy/aptasuite/files/1764118/console_log.txt)
[log_2018-02-27_18-13-06.txt](https://github.com/drivenbyentropy/aptasuite/files/1764119/log_2018-02-27_18-13-06.txt)
[configuration_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1764120/configuration_txt.txt)

**Comment by drivenbyentropy** [comment]
AptaSuite makes use of parallelism as often as possible. You can control the maximal number of cores by going to `Preferences` -> `Number of Cores` and selecting a lower count. 

Overheating should not be an issue on modern systems as virtually any CPU auto-throttles when the temperature hit above a critical level. 

As for the issue you reported, I will look into it :+1:

**Comment by drivenbyentropy** [comment]
This bug is getting annoying ;-). 

I have now set the locale to `en_US` globally for the duration of the application executing. Please let me know if this solves the issue. 

New version is [v0.6.7](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.6.7)

**Comment by PJpb** [comment]
Works fine :)
