### ISSUE TITLE
GUI v0.6.7 - Motif Analysis silent error

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#34]
I run an analysis of two dummy samples, and after clustering I run the motif analysis. Then I clicked around the motifs a little bit and I run the AptaTrace again with a slightly different setup. Everything worked fine, but the console produced some error messages nontheless (but the whole program still works fine). Here are the logs if you wish to deal with that "silent" bug:
[log_2018-02-28_09-23-08.txt](https://github.com/drivenbyentropy/aptasuite/files/1766474/log_2018-02-28_09-23-08.txt)
[configuration_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1766475/configuration_txt.txt)
[console_log.txt](https://github.com/drivenbyentropy/aptasuite/files/1766473/console_log.txt)

**Comment by drivenbyentropy** [comment]
You are too observant ;-)

Fixed in [v0.6.9](https://github.com/drivenbyentropy/aptasuite/releases)
