### ISSUE TITLE
Launch aptasuite 0.7.0

### ISSUE THREAD

**Issue by adrienHenriques** [drivenbyentropy/aptasuite#38]
Hi ! 
I have opened this ticket because the graphic interface of aptasuite 0.7.0 refuse to be launched. I'm on Ubuntu 14.04 LTS. 

Here is a screen of the terminal when I launch it (I don't know if it can help you to solve it).
![image](https://user-images.githubusercontent.com/25905867/36975019-09947ac8-2079-11e8-959a-2a453fe4ac66.png)

Thank you. 
Adrien

**Comment by drivenbyentropy** [comment]
I apologies, I kept some code specific to my development machine active. I will fix this within the next couple of hours.

**Comment by drivenbyentropy** [comment]
I have just released a fix for this issue. Please let me know if [v0.7.1](https://github.com/drivenbyentropy/aptasuite/releases) works for you.

**Comment by adrienHenriques** [comment]
It works perfectly (v0.7.2) ! Thank you very much !
However, is it possible to export data generated by AptaMut ? This could be very useful.

Thank you. 
Adrien

**Comment by drivenbyentropy** [comment]
Good idea. I have added a feature request to the ticket system (see #39). I cannot give you an ETA but it will be added eventually.
