### ISSUE TITLE
AptaMUT "No content in table"

### ISSUE THREAD

**Issue by CentauriAlex** [drivenbyentropy/aptasuite#42]
Hi, 

Awesome progress on the GUI! 

I've been re-analysing some of my data with the v0.8.4 release but when I run AptaMUT the window that opens is empty and there is no Log score:

![image](https://user-images.githubusercontent.com/31040391/39428059-f5c9eb28-4c7d-11e8-95bf-b43847a42f09.png)

I have tried with different rounds and clusters but all are the same.

Thanks

**Comment by drivenbyentropy** [comment]
Hi,

Thanks for reporting this. How many sequences does the cluster you are applying `AptaMut` on have? AptaMut requires clusters with at least two members to compute the score.

**Comment by CentauriAlex** [comment]
Hi, 

They have several hundred to several thousand members.

**Comment by drivenbyentropy** [comment]
That is interesting. Could you please try the following (each time restarting the GUI if possible)?

Start the GUI from command line and watch for error while:
1) Open the `Aptamer Family Analysis` tab, select a cluster on the left panel and immediately click the `AptaMut` button.
2) Open the `Aptamer Family Analysis` tab, select one arbibrary aptamer from the table and dtart `AptaMut`
3) Open the `Aptamer Family Analysis` tab, select the first 15 aptamers (multiselect with Shift) and start `AptaMut`

Meanwhile I will try to recreate this issue locally. Thanks!

**Comment by CentauriAlex** [comment]
So having restarted the GUI I still can't get it to work. 

However it appears if I compare:
Negative Selection Round with Negative Reference Cycle = works
Negative Selection Round with Positive Reference Cycle = does not work
Positive Selection Round with Negative Reference Cycle = works
Positive Selection Round with Positive Reference Cycle = does not work

I tried the 3 scenarios you suggested above using the largest cluster (>170,000 members) using a Positive Selection Round with Positive Reference Cycle but still no luck. 

Thanks

**Comment by drivenbyentropy** [comment]
Now we are on to something! I tried to recreate this locally and it was always working. What I failed to test however, where using negative selection cycles. I believe I am not taking this scenario into account when initializing `AptaMut`.

I will try to push out a new version with a fix later today. Thanks again for going through the tests.

**Comment by drivenbyentropy** [comment]
I might have spoken too soon. Even if I try the combinations you mentioned with my test data set I cannot reproduce your results. Here is what I suspect might be happening. `AptaMut` only works on the subset of sequences that are present in the selected cluster in both, the current selection cycle and the reference cycle. My suspicion is that in the above combinations which do not work, there is no overlap between these sets. One hint towards this might be to have a look at the Cluster Enrichment Plot. If you select the corresponding cycle in the "Compare to"  drop-down box for the cases that do not work, you should not get any data on the scatter plot. In contrast in the cases it did work, you should see it. 

I am also open to the idea of adding an option to `AptaMut` for treating missing sequences in the reference cycle as a count of 1 (0 would not work to compute an enrichment value). However, I am not sure how accurate the prediction would be as a result. Let me know what you think.

**Comment by CentauriAlex** [comment]
There should be a lot of overlap, for the two positive cycles I can't get to work the Cluster Enrichment Plot is below:

![image](https://user-images.githubusercontent.com/31040391/39467108-36e8215a-4d24-11e8-8164-e01c8a6186e6.png)

**Comment by drivenbyentropy** [comment]
Thank you for this information. If possible, could you start `AptaSuite` from command line, and run `AptaMUT` for the above two cycles again and post the console output here? I am curious to know if there is any output on the console after the following message: 
```
Initializing AptaMUT content
```

Sorry for the inconvenience and thanks!

**Comment by CentauriAlex** [comment]
No problem, having run the AptaMUT there is no output in the console after that line although I did encounter an error, please see below:

Extracting aptamers for cluster 8570101
Determining cluster diversity
Determining cluster membership of aptamers
Extracting aptamer sizes
Exception in thread "Thread-21" java.util.NoSuchElementException
	at org.mapdb.BTreeMap$entryIterator$1.next(BTreeMap.kt:1174)
	at org.mapdb.BTreeMap$entryIterator$1.next(BTreeMap.kt:1172)
	at lib.aptamer.datastructures.MapDBAptamerPool$InverseViewPoolIterator$1.next(MapDBAptamerPool.java:998)
	at lib.aptamer.datastructures.MapDBAptamerPool$InverseViewPoolIterator$1.next(MapDBAptamerPool.java:978)
	at gui.core.motifs.MotifAnalysisRootController$9.run(MotifAnalysisRootController.java:1110)
	at java.base/java.lang.Thread.run(Thread.java:844)
Sorting cluster members
Initializing AptaMUT content

Having re-run the same, the above error seems to have disappeared:

Extracting aptamers for cluster 8570101
Determining cluster diversity
Determining cluster membership of aptamers
Extracting aptamer sizes
Sorting cluster members
Initializing AptaMUT content



The table appeared with no content in each case, please see below:

![image](https://user-images.githubusercontent.com/31040391/39804027-dda42240-536a-11e8-82c9-b16232e4184b.png)

**Comment by drivenbyentropy** [comment]
Thank you for getting back to me on this. I would like to provide you a custom version of AptaSuite with additional debugging code to get to the bottom of this. If you are willing to continue in helping to find this bug, please let me know and I will compile the program for you.

**Comment by CentauriAlex** [comment]
Sure, no problem.

**Comment by CentauriAlex** [comment]
Great, having tried v0.8.7 the AptaMUT now works for my positive selection cycles! However in this version many of the radio buttons and some menus disappear when going over them with the mouse pointer, please see screen shots below:

![image](https://user-images.githubusercontent.com/31040391/39915743-a0fde99c-5500-11e8-8941-97abddad3724.png)

![image](https://user-images.githubusercontent.com/31040391/39915753-a7505384-5500-11e8-9084-39669a18fd76.png)


This appears to happen to varying degrees on every tab.

Thanks

**Comment by drivenbyentropy** [comment]
I am glad to hear the main issue is solved. I have also encountered the issue with the white boxes in the past and I honestly have no idea where it comes from. I think this is related to the GUI relying on multithreading but there is no error message anywhere. The only thing that was consistent for me is that this happens when you resize the GUI while it is performing an operation (i.e. a loading layer is visible). 

If you could, please try to resize the GUI when no operations are taking place and let me know if you can reproduce my findings.

Thanks again.
