### ISSUE TITLE
Export Data Window bug

### ISSUE THREAD

**Issue by CentauriAlex** [drivenbyentropy/aptasuite#43]
Hi, 

When I try to export data the window that opens is missing some text at the top and the window is not re-sizeable:

![image](https://user-images.githubusercontent.com/31040391/39433784-ad560d5c-4c8e-11e8-9060-917862db3b2b.png)

Also I am unable to select the "compress files" or with "primers options" in the additional options section.

Thanks

**Comment by drivenbyentropy** [comment]
Thank you for reporting this. I have fixed the issue and it will be made available in the next release.
