### ISSUE TITLE
AptaMUT

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#48]
Hi there!
Thanks for the constant updates, nice to see some implementations I've suggested :)

Would you mind explaining the AptaMUT a little bit closer? I can't get to work it out well...

Thanks!
PJ

**Comment by drivenbyentropy** [comment]
Hi, 

AptaMut is explained in detail [here](https://www.ncbi.nlm.nih.gov/pubmed/25870409). In principle, AptaMut attempts at estimating the likelihood that a mutant in a cluster with was measured to be of increased cycle-to-cycle enrichment compared to the parent sequence is truly a better binder as the wildtype. It does so by providing you with a log-score reflecting the log of the ratio between the expected enrichment of that mutant and the measured one. 

Hope this helps.

**Comment by PJpb** [comment]
It does, thank you!
