### ISSUE TITLE
Motif analysis crashes (v0.8.9)

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#49]
Hi,
I've tried to run the motif analysis (AptaTrace) on my data (full selection data, cluster-analyzed; in GUI v0.8.9, run in Win10 through PowerShell as Administrator) with default setup, after the prompt that I have to predict the secondary structure profiles and pressing OK the program crashes. Here are the logs:
[log_2018-06-19_08-23-05.txt](https://github.com/drivenbyentropy/aptasuite/files/2114242/log_2018-06-19_08-23-05.txt)
[190618_error_console_log.txt](https://github.com/drivenbyentropy/aptasuite/files/2114243/190618_error_console_log.txt)

**Comment by drivenbyentropy** [comment]
Thank you for reporting this. 

From what I can see based on the logs, this is caused by an ```java.nio.file.AccessDeniedException``` when trying to create and/or access the structuredata folder. As such I believe this might be an OS related issue: 
```
Caused by: java.nio.file.AccessDeniedException: D:\bioIT\DATA\xxx\2150618\structuredata
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(Unknown Source)
        at java.nio.file.Files.createDirectory(Unknown Source)
        at java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
        at java.nio.file.Files.createDirectories(Unknown Source)
        at lib.aptamer.datastructures.MapDBStructurePool.<init>(MapDBStructurePool.java:144)
```

My suggestion would be to try the following:
* Manually delete the ```structuredata``` folder from the project and run the structure prediction again using the command line, i.e. ```java -jar aptasuite.jar -predict structure -config path/to/config/file``` to see if the problem persists.
* Move the experiment folder to a different location (no network drive). 
* Make sure that you have write permissions for the parent folder

Please let me know if this solves the issue. If not, I will need to find a way to replicate this problem somehow.

Thanks!

**Comment by PJpb** [comment]
Thanks for the reply.

The drive is a local SSD drive, and there were no problems before. I'm using Windows 10, and I run the AptaSuite from PowerShell console with administrator privileges. There is no problem with the perimissions in this setup. Also, the folder /structuredata does not exist when I try to run the AptaTrace.

Also, I've tried to create the folder /structuredata manually, but it doesn't help - in fact, the software removes this folder after the crash! (So maybe it removes it prior to the crash and then it cannot find it so it crashes?)

I'll try to run the structure prediction from the console next week and I'll let you know.

**Comment by PJpb** [comment]
So I've finally got a chance to run the structure prediction from command line. I've used PowerShell with admin rights. It crashed just after loading all the data. Here are the logs:
[log_2018-06-28_18-30-31.txt](https://github.com/drivenbyentropy/aptasuite/files/2146635/log_2018-06-28_18-30-31.txt)
[280618_error_console_log.txt](https://github.com/drivenbyentropy/aptasuite/files/2146636/280618_error_console_log.txt)
And the configuration file:
[cfg2_280618_structures.txt](https://github.com/drivenbyentropy/aptasuite/files/2146638/cfg2_280618_structures.txt)

Hope you can solve it!
Best,
PJ

**Comment by PJpb** [comment]
Hi,
I've managed to start the structure prediction in v0.9.0 from command line (Windows PowerShell with administrator privileges). The GUI still crashes with the same errors as above, even if the GUI is started via administrator-enabled PowerShell.

FYI running the structure prediction on a laptop computer does take a while, even with full processor use (i7-7700-HQ @ 2.8GHz, 8 threads, ~95% usage all the time) the prediction speed is about ~100 structures per second. But doable :)

**Comment by drivenbyentropy** [comment]
@PJpb I am sorry for the late response but please give it a try now. I believe I have identified and fixed the bug which was causing this. Turns out is was a windows specific issue based on how files and directories are handled on this platform.
