### ISSUE TITLE
AptaPLEX cycles export

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#5]
Hi,
When using option _-parse -export cycles_ my exported .fasta data looks like that:
`>AptaSuite_1|test|length=43
71846584656767847167657167847165717167716767716571716565676767716771846567718471848471`
Why and how to change it to sequences?

Best,
PJ

**Comment by drivenbyentropy** [comment]
Hi and thank you for reporting this. 

This is a bug and it will be fixed in the next release. Internally, AptaSUITE stores sequences as byte arrays and I forgot to convert them back to string before writing them to file. What you see here is the ASCII representation of the sequences, i.e:
* A = 65
* C = 67
* G = 71 
* T = 84

Meanwhile, you could try exporting the sequences in fastq format (configuration parameter `Export.SequenceFormat = fastq `) which should not have this issue and then use a converter to fasta.

My apology for this and thanks again!

**Comment by drivenbyentropy** [comment]
I have published a new release. 

Could you please try with version [v0.4.3](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.4.3) and let me know if it fixes the issue?

Thanks!

**Comment by PJpb** [comment]
Hi,
The bug is fixed, thank you for your quick reaction!
best,
PJ

**Comment by drivenbyentropy** [comment]
Thanks for getting back to me. I will remove the debugging information (which are from third party libraries) with the next version.

**Comment by PJpb** [comment]
Hi,
I did a recheck on the data exported, and unfortunately it's still bugged. option _-export cycles_ exports the sequences which length is the length of the random region given in the config file, but they start with the primer region. In effect, what we obtain, is the primer region and a truncated random region.
Example:
`Config file:
Experiment.primer5 = **GTATACCTGCAGCTGAGG**
Experiment.primer3 = GATGACACTACGTGACCA`
(_Random region_ of my aptamers was 44 nucleotides, but it was not set in the config file)
`Analyzed sequence:
@MG00HS14:636:C8CGUACXX:5:1101:2735:1985 1:N:0:CTTGTA
TTGTAGACTCG**GTATACCTGCAGCTGAGG**_TTGCCGCGCACCAGTCGTTCATAGATGTCGTTGGCGTGTTGCGC_GATGACACTACGTGACCACGAGTCGCAGA
+
DA>CDDDEFGHHHHHIHHHIJEFHIJGGIGHHIGFGIIIJDFHHIJGGEEEHHEFHGHGIIHDJHIHHJJIGJIIHEHGEIGIJJJIGHGHHHFFFFDCCB3`
`Exported:
>AptaSuite_1|test|length=44
**GTATACCTGCAGCTGAGG**_CAAAGTGACACAGGAGTCTGCGAGGG_`

**Comment by drivenbyentropy** [comment]
You are correct, this is indeed another bug which was introduced when I failed to update this export class upon some changes in representing aptamers internally. 

Please let me know if [v0.3.4b](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.4.3b) fixes the issue. 

Thanks again for reporting this.

**Comment by PJpb** [comment]
It's fixed in v0.3.4b, many thanks!
