### ISSUE TITLE
Ways to make Data Import run faster

### ISSUE THREAD

**Issue by drthanwho** [drivenbyentropy/aptasuite#52]
Is there anyway to make the program and at least the Import step run any faster?

I have 80million sequences and it is of course taking days to import...

I tried to increase the memory it can use but it will not use more than 1.2GB. Is memory not making a significant change on this step or am I doing something wrong here?

**Comment by drthanwho** [comment]
After looking into tnis, the problem was not opening the program through powershell. And making sure you have 64bit Java installed. 

After these are done the program can use 2+GB easily :smile:

**Comment by drivenbyentropy** [comment]
My appologies for the late reply, I was traveling. I have added this information to the [Wiki](https://github.com/drivenbyentropy/aptasuite/wiki/System-Requirements) so others can benefit from this knowledge as well.

Thanks for reporting this!
