### ISSUE TITLE
Add the ability to import demultiplexed data containing only the randomized region to AptaPLEX

### ISSUE THREAD

**Issue by drivenbyentropy** [drivenbyentropy/aptasuite#53]
* Add option "Data includes primers" to configuration file to allow importing data consisting only of the randomized region size.

**Comment by zaklmurray** [comment]
Hi there, 

Has this option already been added into the functionality of the software? If not, when do you think it is likely to be added and is there anyway around not having the primer sequences in the data? 

Regards, 
Zak

**Comment by PJpb** [comment]
Hi,
I don't know if you've thought of that, but if you are on hold due to lack of this feature, you can always artificially add some primers to your data.

Also, out of curiosity - how did you get to the point when you've got this data with no primers at all?

Regards,
PJ

**Comment by zaklmurray** [comment]
Hi PJ, 

Thanks for your quick reply. 

I had thought of adding primers artificially. I have tried it and the tool is working nicely with the artificial primers. 

The reason that I got to that point, was that the sequencing supplier provided the data with the primers already trimmed off for some reason. I am going to ask them to send me the raw data as well, as I would like to do the trimming myself. 

Cheers, 
Zak

**Comment by drivenbyentropy** [comment]
Hi, 

As @PJpb  has stated, this feature is not available as of yet and the workaround is to add artificial primers. I will look into implementing this and #59 for the next release. Unfortunately I cannot provide an ETA at this moment but I will do my best to be fast.

Thanks!

**Comment by drivenbyentropy** [comment]
@zaklmurray This feature is now available as of ```AptaSuite v0.9.1``` and above. The parameter ```AptaplexParser.OnlyRandomizedRegionInData``` has been added to control this feature (initially set to ```false```). In the GUI you can select this feature under the ```Advanced Options``` section of the ```New Experiment``` wizard. There you will find it in the ```Aptamer Properties``` tab. Please note that this feature is only available if your data is demultiplexed (i.e. one/two file(s) per round depending if paired end or not). The assumption here is that if the primers are missing, so are the barcodes.

Please let me know if you have any further issues and thanks again for suggesting this.

**Comment by drivenbyentropy** [comment]
Closing 149872af9e244c0d6076b2dbe754d1c2f8c13a22.
