### ISSUE TITLE
Diversity calculation every time you click on a different cluster

### ISSUE THREAD

**Issue by drthanwho** [drivenbyentropy/aptasuite#55]
I'm not sure how other people work. But personally having 150 million sequences to work with I had to do all the analyses on a supercomputer server and then move all the files in a local windows computer in order to use the GUI and visualise the analyses. 

Every time you move between different clusters the GUI starts calculating the cluster diversity, which takes a significant amount of time. This happens even if you go back to the same cluster.

Perhaps this could be something previously calculated so it doesn't have to re calculate it every time you look at a different cluster?

**Comment by drivenbyentropy** [comment]
Thank you for your comment. You are correct in that Cluster Diversity and other information are currently being computed on the fly each time a particular screen is opened. I will look into adding lazy loading for these type of information so that these values only have to be computed once.

**Comment by drivenbyentropy** [comment]
@drthanwho It took me a while but as of ``AptaSuite v0.9.3``, lazy loading should work in the ``Aptamer Family Tab`` and the results of long computations are stored on disk for later retrieval. If you have the opportunity to test this feature and provide feedback, I would greatly appreciate it.

Thanks!
