### ISSUE TITLE
AptaSuite not taking advantage of multiple cores

### ISSUE THREAD

**Issue by drthanwho** [drivenbyentropy/aptasuite#57]
Hey, 

I have been noticing that when Aptasuite is trying to load information (only confirmed for the clusters page so far) it is only using one of the four available cores, which results in each cluster taking 30+ mins to load. However, in a few rare occasions it has used all four cores and loaded clusters withing a couple minutes.

I was wondering if this is a bug or limitation of the program? Has anyone else experienced this? 

![image](https://user-images.githubusercontent.com/22405505/44082339-32ea7992-9fb1-11e8-8fc4-eca63545baf5.png)

**Comment by drivenbyentropy** [comment]
Hi,

When loading the different pages in the GUI, AptaSuite is not bound by CPU speeds but by data I/O. While I did implement this process in a threaded fashion, in my experience, it is the hard drive speed which makes most of the difference in terms of loading speed. 

Do you have an SSD or a traditional HDD in you system? Given the amount of data HT-SELEX constitutes, I would recommend at least an SSD or, even better, a modern M.2 drive. 

I do plan to look into further optimizing this in the future, however it might take me a while to get to it.

Hope this helps!

**Comment by drivenbyentropy** [comment]
Closing. LazyCache should improve the user experience related to this ticket. Please reopen if you still have an issue with this.
