### ISSUE TITLE
Invalid cycle output file [enchancement]

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#59]
Hi,
Lately analysing my data I'm having quite a lot of Invalid cycle reads. I'm still wondering and searching if it's my fault or the software's, but that's quite tedious. What would help quite a bit is an output file(s) generate during the parsing, containing all the sequences which were not accepted as correct reads. One could then analyse what went wrong more easily then now.
Thanks! :)
PJ

**Comment by drivenbyentropy** [comment]
Hey, 

Good idea, and quickly implementable. Will add it in the next version, thanks!

**Comment by drivenbyentropy** [comment]
Closing 149872af9e244c0d6076b2dbe754d1c2f8c13a22.
