### ISSUE TITLE
Exception in thread "pool-1-thread-1" ...

### ISSUE THREAD

**Issue by khuntco** [drivenbyentropy/aptasuite#60]
Received the following error after running the follow job:

java -jar aptasuite-0.9.2.jar -parse -predict -trace -config

```
Exception in thread "pool-1-thread-1" java.lang.NullPointerException           
	at lib.parser.aptaplex.FastqReader.getNextRead(FastqReader.java:126)
	at lib.parser.aptaplex.AptaPlexProducer.run(AptaPlexProducer.java:180)
	at java.lang.Thread.run(Thread.java:745)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by drivenbyentropy** [comment]
Hi,

Have you provided a configuration file after the ``-config`` parameter? If not, please have a look in the [wiki](https://github.com/drivenbyentropy/aptasuite/wiki/The-configuration-file) as to how to create it for your experiment.

**Comment by khuntco** [comment]
Sorry I should have specified that I do have a config and a path to the config.cfg file.

This occurs after successful initialization and specifically occurs during the AptaPlexParser run

![screenshot from 2018-10-09 13-07-54](https://user-images.githubusercontent.com/44004950/46695446-6b5bb180-cbc4-11e8-8c47-9d03b49849c8.png)

**Comment by drivenbyentropy** [comment]
Thanks for the clarification. It looks to me that the ``NullPointerException`` might be occurring when reading the last read of the fastq file. Based on the number of total reads, would you be able to verify this for me? 

I will then see if I can reproduce this issue locally.

Thanks!

**Comment by khuntco** [comment]
> Thanks for the clarification. It looks to me that the `NullPointerException` might be occurring when reading the last read of the fastq file. Based on the number of total reads, would you be able to verify this for me?

I went to verify my last round .fastq file and sure enough it had been altered and damaged. After fixing this issue, AptaplexParser completed with no faults.

Thanks for your help.

**Comment by drivenbyentropy** [comment]
Great! Glad the issue got solved.
