### ISSUE TITLE
Cluster Cardinality Chart not being stored in LazyCache

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#63]
I don't know if that is on purpose, but the Cluster Cardinality Chart is being computed each time you open a cluster (despite the fact if it was or wasn't analyzed before).
If that is on purpose please close the ticket.

**Comment by drivenbyentropy** [comment]
This is intentional as is should be a quick thing. The cluster sizes and diversities are stored in the instances of the corresponding cycles and should hence take atomic time to retrieve. Do the charts take long to generate in your case?

**Comment by PJpb** [comment]
The Logo, mutations and cluster cardinality chart take some time depending on the size of the cluster. If it's a small one (diversity is a few dozen) then it might take up to about half a minute, if it's a large cluster then it will take a few minutes. I am however using a laptop computer (a decent one, but still) with Windows 10 Home, so I'm not expecting too much ;)

**Comment by PJpb** [comment]
Just wanted to let you know that the Lazy Cache works perfectly now, can switch around with no obstacles, loads everything really quickly. Great job, thanks! Makes life much easier :) 🥇
