### ISSUE TITLE
Issue with GUI crashing when opening experiment 

### ISSUE THREAD

**Issue by zaklmurray** [drivenbyentropy/aptasuite#65]
Hi there, 

I am running the latest version of AptaSuite on a Macbook Pro, running macOS High Sierra. 

I click on the .jar file, the GUI launches and the functionality seems fine. 

I have run some analysis using the command line version of the tool on an HPC and have copied the files on to my local machine so that I can visualise the data. When I open the configuration file on my local machine, the GUI immediately starts to process the file but then closes after about 2 seconds and I can't view the data. 

Has anyone else had a similar issue? Is there any other way I can visualise the data without the GUI? 

Kind Regards, 
Zak

**Comment by drivenbyentropy** [comment]
Hi Zak,

Thank you for reporting this. Could you please start AptaSuite in GUI mode from the command line, repeat the process and paste the command line output here? 

This should give be a better idea of what is going on. 

You can start AptaSuite in command line mode by starting the jar file without any parameters: ``java -jar path/to/aptasuite-x.y.z.jar`` 

Thanks!

**Comment by zaklmurray** [comment]
No worries. 

I tried this today and I am still getting the same error. I have also tried to run it on a Windows PC as well and got the same error. 

Just a couple of quick questions: 

I assumed that because the back-ends are the default and there is only one option, they don't need to be specified in the configuration file? Is that correct? 

Kind Regards, 
Zak

**Comment by drivenbyentropy** [comment]
Thanks for testing this. You are correct, the backends do not have to be specified. 

I have been looking into this bug and I believe it might be caused by faulty check of whether the ``Experiment.projectPath`` exists on disk, returning true even though it is not the case. This then causes the logger to create a directory where it should not. 

Therefore I would like to ask you for one last test. Can you again please make sure no ``Experiment.projectPath`` line is present in the configuration file you are planning to open, _rename_ the folder your experiment is in, and then open it again in AptaSuite?

I apologize for the inconvenience.

**Comment by zaklmurray** [comment]
Hi Again, 

I have tested as requested but I am still getting the same error. 

I have noticed a few of things by looking at the log file created when trying to run each experiment. They might indicate something to you about why this is occurring: 

(1) You seem to be correct - since no Experiment.projectPath is specified, the program assumes that the projectPath is the parent folder of the configuration file which seems to be fine in this case. 

(2) The program is able to find the pooldata and cycledata folders correctly, however when it states "Found and loaded a total of 0 aptamers from disk" when reading from lib.aptamer.datastructures.MapDBAptamerPool. 

(3)  The error and crashing of the GUI always occurs when processing Round 4 (out of 7 selection rounds). When the log states: "Processing selection cycle Standard Conditions - Round 4". 
- I have re-downloaded and replaced the Round 4 file but this doesn't resolved the issue. 

Hopefully this helps. I have attached the log file below for your reference:

[log_2018-10-29_13-09-48.txt](https://github.com/drivenbyentropy/aptasuite/files/2523372/log_2018-10-29_13-09-48.txt)

If you need me to test anything else or send you the files then I am happy to do so. 

Regards, 
Zak

**Comment by drivenbyentropy** [comment]
@zaklmurray my appologies for the delay. I have issued a new version of AptaSuite. Could you please check if your issue persists with ``v.0.9.4``? 

Thanks!

**Comment by zaklmurray** [comment]
@drivenbyentropy, no worries! Thank you for taking a look into this, it is much appreciated. I will download and try the new version today and get back to you. 

Regards, 
Zak

**Comment by drivenbyentropy** [comment]
Awesome thanks. New version is still building and should be up within the next 30 minutes.

**Comment by zaklmurray** [comment]
Hello again and apologies for the late response. 

I have tried the new version of Aptasuite and I am still getting the same error as with version 0.9.3. 

I did notice that every time the GUI crashes, it is when I loaded the 4th selection cycle of my experiment. In order to see if it was associated with the data for this one round, I commented out that cycle from the configuration file and then the programme crashed when invoking the 5th cycle. Based on this, I am wondering if it is some sort of memory issue? 

If I comment out selection cycles 4,5,6 and 7 from the configuration file then the GUI doesn't crash but there is just no data displayed under any of the tabs. 

If you have any other thoughts on what might help with this issue, then anything would be much appreciated. 

Kind Regards, 
Zak

**Comment by drivenbyentropy** [comment]
Thanks for the report.

This is strange indeed. Based on your logs, you have 128GB of memory, which is a lot. Even with 150 mio sequences in the database you should never run into issues when providing java with that memory. I suggest to try to increase the memory java can use for AptaSUITE. For this, start AptaSuite from the console with 

```java -Xmx75G -jar aptasuite.x.y.z.jar ```

where 75 translates to 75GB of RAM and x.y.z correspons to the version of AptaSuite you are using.

More information can be found in the Wiki under Frequent Issues.

Let me know if this works for you.
