### ISSUE TITLE
change target

### ISSUE THREAD

**Issue by yazdan59** [drivenbyentropy/aptasuite#67]
Dear friends
I want to use "new simulated experiment" section, in order to pick some aptamers based on the simulation result. My question is how could I add a new target molecule in order to find best aptamers binding to it? I could not find any sections related to target definition in the opened dialog box.
Thanks in advanced.

**Comment by drivenbyentropy** [comment]
Thank you for your comment. 

The simulation feature is meant to accurately simulate the statistical selection properties of a SELEX experiment. It does not take into account any structural properties of the aptamers or the target. In other words, it is not capable of realistically simulating a selection in a molecular dynamics kind of sense. To the best of my knowledge, such software does not exist.
