### ISSUE TITLE
time of exucution 

### ISSUE THREAD

**Issue by rihabbbb** [drivenbyentropy/aptasuite#71]

**Comment by rihabbbb** [comment]
i am using aptasuite program it run from 24h and it did'nt finish yet 
it is normal 
thanks

**Comment by drivenbyentropy** [comment]
Can you please provide the log file related to your issue? You can find instructions on how to obtain it in the Wiki.

**Comment by rihabbbb** [comment]
AGACACAGGCTTCCATCC-N57-CGTATAATAGCCTTGCCC
--

**Comment by rihabbbb** [comment]
TGGCTCTGGCTTCCGTCC-N50-CGAGAGAGCCGAACCAGC
