### ISSUE TITLE
Running compiled jar on windows results in immediate error

### ISSUE THREAD

**Issue by mmcneill123** [drivenbyentropy/aptasuite#73]
Windows 10
Double clicking on aptasuite-0.9.3.jar or aptasuite-0.9.4.jar results in the following error message:
Could not find the main class: aptasuite.Aptasuite. Program will exit.

**Comment by drivenbyentropy** [comment]
Are you referring to the precompiled binary from the release page or when compiling the project yourself? If you are referring to the latter,  please make sure to use the `jar` file from the generate `zip` archive and not the one generated during the compilation process. The location of the zip file is described [here](https://github.com/drivenbyentropy/aptasuite/wiki/Compiling-from-source).

**Comment by CaptainValerie** [comment]
same here [https://github.com/drivenbyentropy/aptasuite/issues/74]

**Comment by drivenbyentropy** [comment]
I am closing this for now. Feel free to reopen if this is still an issue.
