### ISSUE TITLE
Error AptamerPool backend 

### ISSUE THREAD

**Issue by CaptainValerie** [drivenbyentropy/aptasuite#74]
#Hello there,

APTASUITE is breaking down instantly on loading a new or already existing data set.
Either while opening APTASUITE data or while uploading a fastq file APTASUITE closes immediately.

The log shows each time two Errors in a row:
   [1:40:36 | SEVERE | Thread-5]: lib.aptamer.datastructures.Experiment
   Error invoking construtor of AptamerPool backend 

   [1:40:36 | SEVERE | Thread-5]: lib.aptamer.datastructures.Experiment
   Error invoking AptamerPool backend 

I downloaded additional javafx and included it in the /lib folder without achieving any change.
I'm using APTASUITE 0.9.4
Maven and Githup are downloaded as well but java files are not installable so how to use them? 

Two log files are attached:
[log_2019-10-10_14-01-25.txt](https://github.com/drivenbyentropy/aptasuite/files/3712426/log_2019-10-10_14-01-25.txt)
[log_2019-10-10_13-40-25.txt](https://github.com/drivenbyentropy/aptasuite/files/3712427/log_2019-10-10_13-40-25.txt)

Thank's for any help in advance!

**Comment by drivenbyentropy** [comment]
Thank you for reporting this.

JavaFX should be installed with your current Java distribution, not included in the `lib` folder. Since you are getting a GUI, it is safe to say that that is the case. I noticed that you are storing your data in a Dropbox folder. The way in which Dropbox handles file/folder permissions is known to interfere with AptaSUITE. Could you please try to move it to a local folder and try again?

Thank you.

**Comment by CaptainValerie** [comment]
Hey there,thanks for this incredible fast response!I already moved the whole package to the Desktop and still get the same result.Might there be any performance restrictions from Windows?Would you accept a Team viewer Support request?Greets from Germany/RegensburgValerie 
-------- Ursprüngliche Nachricht --------Von: drivenbyentropy <notifications@github.com> Datum: 10.10.19  19:00  (GMT+01:00) An: drivenbyentropy/aptasuite <aptasuite@noreply.github.com> Cc: CaptainValerie <valerie.bezler@uni-ulm.de>, Author <author@noreply.github.com> Betreff: Re: [drivenbyentropy/aptasuite] Error AptamerPool backend  (#74) Thank you for reporting this.
JavaFX should be installed with your current Java distribution, not included in the lib folder. Since you are getting a GUI, it is safe to say that that is the case. I noticed that you are storing your data in a Dropbox folder. The way in which Dropbox handles file/folder permissions is known to interfere with AptaSUITE. Could you please try to move it to a local folder and try again?
Thank you.

**Comment by CaptainValerie** [comment]
Hello there,I got it working, it was just the wrong Java Version (32 bit).thanks again, a lot for this fast support!
-------- Ursprüngliche Nachricht --------Von: drivenbyentropy <notifications@github.com> Datum: 10.10.19  20:34  (GMT+01:00) An: drivenbyentropy/aptasuite <aptasuite@noreply.github.com> Cc: CaptainValerie <valerie.bezler@uni-ulm.de>, Author <author@noreply.github.com> Betreff: Re: [drivenbyentropy/aptasuite] Error AptamerPool backend  (#74) There should be no restrictions based on operating system. Just to make sure, when you say you moved the whole package to the Desktop, are you referring to AptaSUITE, or the data you are trying to analyze ? I was referring to the latter, i.e. to make sure that the data you are importing and the project folder, are not located in a Dropbox folder.
As for Teamviewer, I do not provide remote support, sorry.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/drivenbyentropy/aptasuite/issues/74?email_source=notifications\u0026email_token=ANOIHEAZBBUGSPCB3VGK6UDQN5YT5A5CNFSM4I7L7MC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEA5KYPQ#issuecomment-540716094",
"url": "https://github.com/drivenbyentropy/aptasuite/issues/74?email_source=notifications\u0026email_token=ANOIHEAZBBUGSPCB3VGK6UDQN5YT5A5CNFSM4I7L7MC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEA5KYPQ#issuecomment-540716094",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
