### ISSUE TITLE
[Tiny bug]Wrong File Extension 

### ISSUE THREAD

**Issue by Eggsorer** [drivenbyentropy/aptasuite#76]
when I turn on the option where aptaSuite will dump all the rejected sequences into a fastq file, it actually spits out compressed fastq file (fastq.gz). But the file extension shown is .fastq. Once you try to read it as text, you will quickly realize that it is a binary.

----------
I am using the following setting
AptaplexParser.UndeterminedToFile = True

**Comment by drivenbyentropy** [comment]
Thank you for reporting this, I will issue a fix for the next release.
