### ISSUE TITLE
App Crash When Analyzing >2 Rounds - Combining Multiple Experiments

### ISSUE THREAD

**Issue by Bioanalytica** [drivenbyentropy/aptasuite#77]
The Java applet crashed after 8 rounds were configured and imported, after sequential elimination of analysis rounds the maximum allowable was 2, else crash. I analyzed two at a time, is there an easy way to recapitulate the 4 analyzed experiments back into one?

Win10 Pro, Intel Core i5-2400@3.1GHz.

[log_2019-11-26_22-35-08.txt](https://github.com/drivenbyentropy/aptasuite/files/3898205/log_2019-11-26_22-35-08.txt)

**Comment by drivenbyentropy** [comment]
Could this be a case of running out of memory? Could you please check if you can process additional rounds if you [increase the heap space for java](https://github.com/drivenbyentropy/aptasuite/wiki/Frequent-issues)? Thank you.

**Comment by Bioanalytica** [comment]
I re-ran the analysis in command prompt, using the pre-apportioned heap space as suggested, and it appears as though it was successful. When I attempt to open the experiment in the GUI, however, it crashes while loading the data files.
[log_2019-12-02_12-21-54.txt](https://github.com/drivenbyentropy/aptasuite/files/3912421/log_2019-12-02_12-21-54.txt)

**Comment by Bioanalytica** [comment]
I've gotten as far as Generating LSH Buckets, which it apparently freezes/crashes before export. Not sure what the issue is but it must have failed since it didn't make it to the final export command. I've got the command line output (including me restarting the analysis) and the main log file. I've heard this isn't the first time you've handled HE4/CA125 aptamer data, lol.
[log_2019-12-23_20-06-04.txt](https://github.com/drivenbyentropy/aptasuite/files/4032534/log_2019-12-23_20-06-04.txt)
[AptaSuite_cmd_output.txt](https://github.com/drivenbyentropy/aptasuite/files/4032535/AptaSuite_cmd_output.txt)
