### ISSUE TITLE
GUI - parameters for AptaPLEX

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#8]
Hi,
I'm just testing the new GUI - thanks for that, that's awesome! I have a couple of issues though.
I wonder however that there is no options choice for AptaPLEX, e.g. AptaplexParser.PairedEndMinOverlap parameters and alike. The second thing is that during a Wizard setup of a new experiment in not-demultiplexed and paired-end samples, I'm obligated to provide a 3' Index. It's not possible to click "Next" if the 3' Index is not provided. Is that on purpose? Also, if I am to provide the 3' Index and my samples do have it, should I give the sequence exactely as it looks like on the forward strand, or as it is on the reverse strand? This is a bit confusing so an example:
During the pre-NGS PCR i used the same index for both forward and reverse primers. So my primers were (index = ACGTGA):
`Fwd: 5'-ACGTGA-ForwardPrimerSeq-3'`
`Rev: 5'-ACGTGA-ReversePrimerSeq-3'`
So, the PCR product's forward read looks like that:
`5'-ACGTGA-ForwardPrimerSeq-RandomRegion-(reverse complement of ReversePrimerSeq)-TCACGT-3'`
TCACGT is obviously the index in reverse complement. The reverse strand looks exactely the same considering the indexes, but of course with the primer regions other way round.
So now, for this sample - what should I put in the "Index 3'" window? ACGTGA or TCACGT?

I hope I managed to write it clearly enough...

Best regards and keep up the great work!
PJ

**Comment by drivenbyentropy** [comment]
Hi PJ,

Thank you for reporting these issues. I will address these one by one (in separate tickets if appropriate).

**Comment by drivenbyentropy** [comment]
Advanced GUI options for AptaPlex are now available in the advanced option tab of the New Experiment Wizard. See #9 for more details.

**Comment by drivenbyentropy** [comment]
The bug forcing you to enter a 3' index regardless of whether it is present in the data has been fixed. See #10 for the fix.

**Comment by drivenbyentropy** [comment]
And as for the last issue, you could not have described it better. In fact, you described it so well that I shamelessly took your example and added it as a tooltip in the Wizard (hover over either Index labels for it to appear). The orientation is always w.r.t to the forward read. Hence in your case the 3' index would be `TCACGT`.

**Comment by drivenbyentropy** [comment]
All changes have been applied and are now available in the latest release, [v0.5.2](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.5.2). Please let me know if you have any further issues by opening separate tickets (one per concern).

Thanks again for reporting this!

**Comment by PJpb** [comment]
Dear drivenbyentropy,
Thanks for the express update! You're really doing a great job. I'm going back to testing the GUI :)
Best,
PJ

PS: Is it normal that aptasuite-5.0 zip file is 692 MB, and v.5.3.zip is 328 MB?

**Comment by drivenbyentropy** [comment]
You are welcome.
