### ISSUE TITLE
AptaSuite GUI crashing - can you combine experiments after file parsing (Mac)

### ISSUE THREAD

**Issue by kep93943** [drivenbyentropy/aptasuite#82]
I am a Mac user and have little coding experience, but I am trying to learn. I have been able to use AptaSuite to analyze all of my SELEX rounds individually and I have gotten to load up to 3 rounds at once with other experiments, but it crashes once I want to do more. When I use the activity monitor, there is never more than 30-40% of the CPU used at a given time leading up to the crash, so I don't think it has to do with not enough RAM.

**Comment by kep93943** [comment]
Actually it may be a RAM issue since I was able to import more rounds with a slightly higher RAM computer.
Is it possible to merge multiple experiments after parsing the FASTQ files?

**Comment by drivenbyentropy** [comment]
This does indeed sound like you are running out of memory to me. In general, CPU usage is independent of RAM usage. It is currently not possible to merge multiple experiments, sorry. 

How big is your dataset and how much ram do you have available?

**Comment by kep93943** [comment]
All of the fastq files together are 2.86 GB and my personal computer has 8GB of RAM. I was able to run more of the rounds with a computer containing 16GB RAM, but that still isn't enough to do an experiment will all of the data.

**Comment by drivenbyentropy** [comment]
I am closing this as it appears to be a hardware limitation. Feel free to reopen if you believe otherwise. Thanks!
