### ISSUE TITLE
Aptasuite takes long time to run

### ISSUE THREAD

**Issue by vahidhamidi** [drivenbyentropy/aptasuite#98]
Hello
I have recently received my SELEX sequency data and I used Uptasuite program for analysing the data. I want to know if it is normal for the program to run for more than 18 hours?
I also provided the information for the log file below. 
Thanks.
Vahid

[log_2021-02-16_19-16-00.txt](https://github.com/drivenbyentropy/aptasuite/files/5999168/log_2021-02-16_19-16-00.txt)

**Comment by drivenbyentropy** [comment]
Closing this, please feel free to reopen if this is still an issue.
